### PR TITLE
Revert "Update prod.tfvars CCD FPs"

### PR DESCRIPTION
**Pull request by nathan-clark**
Reverts hmcts/azure-platform-terraform#692
RDM-11476, as per Mutlu, needs SECOPS approval

### CODE REVIEW

**Review by MSancaktutar — APPROVED** [review]
LGTM

**Review by timja — CHANGES_REQUESTED** [review]
these all look like sensible changes and i don't see why secops approval would be needed for this, it's normally only required for disabling a whole rule

**Comment by nathan-clark** [comment]
> these all look like sensible changes and i don't see why secops approval would be needed for this, it's normally only required for disabling a whole rule

what I've been told Tim, let me check with Mutlu again.

**Comment by MSancaktutar** [comment]
> these all look like sensible changes and i don't see why secops approval would be needed for this, it's normally only required for disabling a whole rule

Hi @timja ,

I think it is ideal to give SecOps a chance to check and challenge a change that pulls off a brick from the firewall, before that takes effect in prod. Other teams may find it unnecessary, which I'm not arguing, but for CCD changes I'd insist for a SecOps approval. If SecOps gives an express, written, general authority that applies to all this kind of changes, we can then release them without Change control.

**Comment by MSancaktutar** [comment]
> these all look like sensible changes and i don't see why secops approval would be needed for this, it's normally only required for disabling a whole rule

@timja  - Could approve and merge this based on the above response, please?

**Comment by timja** [comment]
The PR isn't green, builds here take a long time especially if there's frontdoor involved, if you want to go the approval route then sure...

**Review by timja — APPROVED** [review]

**Pull request merged**
