### PR TITLE
DTSPO-9055 - Add cert to plum aat

### PR DESCRIPTION
**Pull request by endakelly**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSPO-9055

### Change description ###
Wildcard cert missing for plum aat
Currently on microsoft managed as a result.
Will have to remove plum from frontdoor and re-add if this fails.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by timja — CHANGES_REQUESTED** [review]
why are you not using microsoft managed?

**Comment by endakelly** [comment]
> why are you not using microsoft managed?

It is using microsoft managed at the moment but the pipeline tests are throwing an error which I thought would be solved by using the wildcard:

```
Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: plum.aat.platform.hmcts.net. is not in the cert's altnames: DNS:*.azureedge.net, DNS:*.media.microsoftstream.com, DNS:*.origin.mediaservices.windows.net, DNS:*.streaming.mediaservices.windows.net
```

**Comment by timja** [comment]
sounds like a valid error? should have a valid cert

**Comment by endakelly** [comment]
Tests are working for stg now. Must have needed time for the cert to propagate or something.

**Comment by timja** [comment]
> Tests are working for stg now. Must have needed time for the cert to propagate or something.

yeah it takes some time for the first time

**Pull request closed without merging**
