### PR TITLE
Update prod.tfvars ▒▒▒ PLEASE DO NOT MERGE AWAITING SECOPS ▒▒▒

### PR DESCRIPTION
**Pull request by nathan-clark**
https://tools.hmcts.net/jira/browse/RDM-11651

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by MSancaktutar — CHANGES_REQUESTED** [review]
I recall there were some other blockages since shortly after the previous exclusion. Please see the dashboard content with a wider date interval.

**Comment by nathan-clark** [comment]
> I recall there were some other blockages since shortly after the previous exclusion. Please see the dashboard content with a wider date interval.

added _sm_au_c

**Review by MSancaktutar — COMMENTED** [review]
LGTM

**Review by MSancaktutar — APPROVED** [review]
LGTM

**Review by cakeben — APPROVED** [review]

**Pull request merged**
