### PR TITLE
Create demo integration environment

### PR DESCRIPTION
**Pull request by vijayrajagopalan-hmcts**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RDCC-2790

### Change description ###
Create a demo integration environment for RD Professional API

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by adusumillipraveen — COMMENTED** [review]
I have my reservations on allowing this int approach, we are taking many steps back from continuous delivery.

**Comment by vijayrajagopalan-hmcts** [comment]
> I have my reservations on allowing this int approach, we are taking many steps back from continuous delivery.

Business have taken the decision to proceed in this approach. XUI have already setup the INT environment.

**Comment by naikajah** [comment]
@vijayrajagopalan-hmcts  you should be able to approve and merge this within your team.

**Comment by jordankainos** [comment]
PR is stale, can be reopened if deemed valid.

**Review by SujeethKumarAri — APPROVED** [review]

**Pull request merged**
