### PR TITLE
RDO-8162 additions for multiple match_conditions in FW

### PR DESCRIPTION
**Pull request by noferrets**
```
[ ] Yes
[ ] Shhhh
```

### CODE REVIEW

**Comment by noferrets** [comment]
I was following the advice from @henrydobson. I did suggest this was a breaking change but was advised to proceed this way. Adding a DO NOT MERGE flag as testing is sufficient for now until I understand what I've failed to understand about this process. 
 
> 
> Are you just testing this / validating it?
> 
> There's other envs to update: https://github.com/hmcts/azure-platform-terraform/search?q=IPMatchWhitelist&unscoped_q=IPMatchWhitelist

**Comment by noferrets** [comment]
Sorry. re-added DNM as need to get a change written and approved first.

**Comment by timja** [comment]
> Sorry. re-added DNM as need to get a change written and approved first.

this isn't changing anything?

**Comment by noferrets** [comment]
[CHG5001638](https://mojcppprod.service-now.com/nav_to.do?uri=change_request.do?sys_id=e2dd4cdb1bbd9814d9b81f4c2e4bcbed) requested and awaiting approval.

**Comment by noferrets** [comment]
> 
> 
> > Sorry. re-added DNM as need to get a change written and approved first.
> 
> this isn't changing anything?

I've not tested the change. So following change process to CMA.

**Comment by isherraikmo** [comment]
PR checks passed here: -

https://dev.azure.com/hmcts/CNP/_build/results?buildId=71674&view=results

but for some reason not updating status in this PR. merging anyway

**Pull request merged**
